# Generated by Django 5.2.4 on 2025-08-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('golosinas', 'Golosinas'), ('salados', 'Salados'), ('gaseosas', 'Gaseosas'), ('galletitas', 'Galletitas'), ('ramen', 'Ramen'), ('postres', 'Postres'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
