# Generated by Django 5.2.4 on 2025-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Golosinas', 'Golosinas'), ('Salados', 'Salados'), ('Gaseosas', 'Gaseosas'), ('Galletitas', 'Galletitas'), ('Ramen', 'Ramen'), ('Postres', 'Postres')], default='Golosinas', max_length=50),
        ),
    ]
