# fly.toml app configuration file for gomesama-backend
app = "gomesama-backend"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[env]
  DJANGO_SETTINGS_MODULE = "gomesama_backend.settings"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
